FML Project: Logistic Regression

In [2]:
import numpy as np
import pandas as pd

In [3]:
npys_dir = '/home/abhishekjagushte/Labs/FML/project/npys'
X_npy = np.load(npys_dir+'/x_balanced.npy', allow_pickle=True)
y_npy = np.load(npys_dir+'/y_balanced.npy', allow_pickle=True)

In [4]:
df_X = pd.DataFrame(X_npy)
df_y = pd.DataFrame(y_npy)

In [5]:
df_X

,0,1,2,3,4,5,6,7,8,9,...,68,69,70,71,72,73,74,75,76,77
0,53.0,1.560000e+02,2.000000,2.000000,64.000000,96.000000,32.000000,32.0,32.000000,0.000000,...,1.0000,32.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0
1,53.0,3.073900e+04,1.000000,1.000000,43.000000,71.000000,43.000000,43.0,43.000000,0.000000,...,0.0000,32.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0
2,443.0,1.198993e+08,64.000000,91.000000,9200.000000,71536.000000,421.000000,0.0,143.750000,181.182273,...,63.0000,20.0,5715991.125,4730455.424,10100000.0,888586.0,9271424.25,812227.4654,9905194.0,7542091.0
3,53.0,6.937900e+04,2.000000,2.000000,78.000000,338.000000,39.000000,39.0,39.000000,0.000000,...,1.0000,32.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0
4,53.0,9.884700e+04,2.000000,2.000000,74.000000,202.000000,37.000000,37.0,37.000000,0.000000,...,1.0000,20.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108995,80.0,5.221606e+06,3.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.0000,32.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0
108996,80.0,5.656768e+06,12.453821,9.635881,1876.212659,10731.054596,489.258475,0.0,140.693404,191.809079,...,5.0299,32.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0
108997,80.0,5.317155e+06,3.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.0000,32.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0
108998,80.0,5.679643e+06,3.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.0000,32.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0
108999,80.0,3.289457e+02,2.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.0000,32.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0

In [6]:
df_y

                       0
0                 BENIGN
1                 BENIGN
2                 BENIGN
3                 BENIGN
4                 BENIGN
...                  ...
108995  Web Attack � XSS
108996  Web Attack � XSS
108997  Web Attack � XSS
108998  Web Attack � XSS
108999  Web Attack � XSS

[109000 rows x 1 columns]

In [7]:
df_X.shape

(109000, 78)

In [8]:
df = pd.concat([df_X, df_y], axis=1)

In [9]:
df

,0,1,2,3,4,5,6,7,8,9,...,69,70,71,72,73,74,75,76,77,0
0,53.0,1.560000e+02,2.000000,2.000000,64.000000,96.000000,32.000000,32.0,32.000000,0.000000,...,32.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0,BENIGN
1,53.0,3.073900e+04,1.000000,1.000000,43.000000,71.000000,43.000000,43.0,43.000000,0.000000,...,32.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0,BENIGN
2,443.0,1.198993e+08,64.000000,91.000000,9200.000000,71536.000000,421.000000,0.0,143.750000,181.182273,...,20.0,5715991.125,4730455.424,10100000.0,888586.0,9271424.25,812227.4654,9905194.0,7542091.0,BENIGN
3,53.0,6.937900e+04,2.000000,2.000000,78.000000,338.000000,39.000000,39.0,39.000000,0.000000,...,32.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0,BENIGN
4,53.0,9.884700e+04,2.000000,2.000000,74.000000,202.000000,37.000000,37.0,37.000000,0.000000,...,20.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108995,80.0,5.221606e+06,3.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,32.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0,Web Attack � XSS
108996,80.0,5.656768e+06,12.453821,9.635881,1876.212659,10731.054596,489.258475,0.0,140.693404,191.809079,...,32.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0,Web Attack � XSS
108997,80.0,5.317155e+06,3.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,32.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0,Web Attack � XSS
108998,80.0,5.679643e+06,3.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,32.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0,Web Attack � XSS
108999,80.0,3.289457e+02,2.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,32.0,0.000,0.000,0.0,0.0,0.00,0.0000,0.0,0.0,Web Attack � XSS

In [10]:
df = df[~df.isin([np.inf, -np.inf]).any(axis=1)]

In [11]:
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
74    0
75    0
76    0
77    0
0     0
Length: 79, dtype: int64

In [12]:
attaktypes={'BENIGN':0, 'Bot': 1, 'DDoS':2, 'DoS GoldenEye':3, 'DoS Hulk':4,
       'DoS Slowhttptest':5, 'DoS slowloris':6, 'FTP-Patator':7, 'Heartbleed':8,
       'Infiltration':9, 'PortScan':10, 'SSH-Patator':11,
       'Web Attack � Brute Force':12, 'Web Attack � Sql Injection':13,
       'Web Attack � XSS':14}
df_y = df_y[0].map(attaktypes)

In [20]:

from sklearn.model_selection import train_test_split

features = df_X
labels = df_y

X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.1, random_state=42)
X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size=0.5, random_state=42)

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import jaccard_score


# import warnings filter
from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)

from sklearn.impute import SimpleImputer
SimpleImputer(missing_values=np.nan, strategy='mean')

model_logistic = LogisticRegression(solver='lbfgs', class_weight='balanced', max_iter=1000, random_state=42)
model_logistic.fit(X_train, y_train), 
predict = model_logistic.predict(X_test)
y_predicted = np.round(predict)
print(classification_report(y_test, y_predicted))

              precision    recall  f1-score   support

           0       0.93      0.55      0.69       777
           1       0.68      0.99      0.80       247
           2       0.76      0.98      0.85       397
           3       0.97      0.95      0.96       566
           4       0.93      0.89      0.91       410
           5       0.90      0.88      0.89       502
           6       0.88      0.82      0.85       517
           7       0.91      0.66      0.76       514
           8       1.00      1.00      1.00       110
           9       0.85      0.92      0.88       102
          10       0.42      0.97      0.59       405
          11       0.99      0.50      0.67       476
          12       0.88      0.09      0.16       253
          13       0.62      0.61      0.61        87
          14       0.28      1.00      0.44        87

    accuracy                           0.76      5450
   macro avg       0.80      0.79      0.74      5450
weighted avg       0.85      0.76      0.76      5450

/home/abhishekjagushte/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [15]:
from sklearn.metrics import f1_score

f1_scores = f1_score(y_test, y_predicted, labels=range(15), average=None)
macro_f1 = f1_score(y_test, y_predicted, average='macro')
micro_f1 = f1_score(y_test, y_predicted, average='micro')

In [17]:
print(macro_f1, micro_f1)

0.7382934467889687 0.7649541284403669